### ISSUE TITLE
uiSettings.overrides.defaultRoute changed in 4.9: /app/wazuh 

### ISSUE THREAD

**Issue by SecurityArsenal** [socfortress/CoPilot#293]
Wazuh 4.9 changed the defaultRoute:

uiSettings.overrides.defaultRoute: /app/wazuh

to 

uiSettings.overrides.defaultRoute: /app/wz-home

So you should update the walk-thru docs.

**Comment by taylorwalton** [comment]
Hey There! I'm sorry but does this pertain to CoPilot? It seems like this pertains to the Wazuh-Indexer?

**Comment by SecurityArsenal** [comment]
For your documentation...  You have your walk thru videos and documents that have people replacing their config files with the ones you provide that are now incorrect.  If they do that they will never get it working as the route has changed to /app/wz-home.  Your documentation is so different now that you made so many changes (for the better), but you don't have any docs that walk thru the current design.  You have it doing all of that when provisioning a customer.  The install is hit or miss if you can figure out all the changes and issues between the different versions if you can even get copilot working correctly.

**Comment by taylorwalton** [comment]
I really appreciate you bringing this up. It sounds like you're frustrated with the changes we've made, and I can understand why. Open-source tools can be difficult to work with because they evolve quickly, and as you've noticed, documentation sometimes struggles to keep up. It can feel like you're getting one version, and the documentation is speaking about another.

In my experience, maintaining balance between contributing to the community and serving clients is always challenging. We do our best to provide for the community, but at the end of the day, our paying clients often take priority, and that can slow down how fast we update documentation.

That said, I’d love to get things back on track for you. Would you be willing to help out with some feedback or even contribute to the documentation so we can get things clearer and more accurate for others facing the same issues?

**Comment by ioscanner** [comment]
I'm not upset with the changes at all; in fact, I think they're great! I'd be happy to contribute by helping update the documentation. Once I get the product up and running, I plan to try out several different installation methods and update the relevant commands. This way, we can provide clear documentation on how to install and update the product as things evolve.

The biggest issue when adding new sections is the lack of upgrade details, which can cause production installs to break. It would be really helpful to include upgrade warnings, especially if changes will break things from previous versions unless specific upgrade tasks are completed. Since we actively use the product, I’m more than willing to help improve the project.

I also think we should consider creating an installer. I'd be happy to write one that can handle a clean install, prepare the system, and install all necessary tools. This would greatly simplify the process. We could develop a single script that installs the software across multiple systems at once, even setting up SSH keys to deploy the software on as many servers/nodes as needed in one go.  Or even a proxmox LXC containers that can spin up quickly.

This approach could potentially be easier and more efficient than using Docker. If we aim for a real installer, I think it would improve performance and simplify updates. We could also look into creating APK or RPM packages instead of Docker images, though that's a conversation we’ll need to have.

**Comment by SecurityArsenal** [comment]
I'm not upset with the changes at all; in fact, I think they're great! I'd be happy to contribute by helping update the documentation. Once I get the product up and running, I plan to try out several different installation methods and update the relevant commands. This way, we can provide clear documentation on how to install and update the product as things evolve.

The biggest issue when adding new sections is the lack of upgrade details, which can cause production installs to break. It would be really helpful to include upgrade warnings, especially if changes will break things from previous versions unless specific upgrade tasks are completed. Since we actively use the product, I’m more than willing to help improve the project.

I also think we should consider creating an installer. I'd be happy to write one that can handle a clean install, prepare the system, and install all necessary tools. This would greatly simplify the process. We could develop a single script that installs the software across multiple systems at once, even setting up SSH keys to deploy the software on as many servers/nodes as needed in one go. Or even a proxmox LXC containers that can spin up quickly.

This approach could potentially be easier and more efficient than using Docker. If we aim for a real installer, I think it would improve performance and simplify updates. We could also look into creating APK or RPM packages instead of Docker images, though that's a conversation we’ll need to have.

**Comment by taylorwalton** [comment]
Thanks so much for your enthusiasm and willingness to contribute—it’s clear you’re deeply invested in improving the product, and that kind of commitment is incredibly valuable. It sounds like you’ve got some excellent ideas, particularly around updating the documentation and simplifying the installation process, which could make a big difference for the community.

I hear you when you mention that the biggest issue has been the lack of upgrade details, especially with the risk of breaking production installs. That’s a valid concern, and it’s something we’ll need to prioritize as CoPilot evolves. Including more specific upgrade warnings could certainly help avoid those headaches. I completely understand how staying up-to-date with a rapidly moving Beta product can be a challenge, especially with new releases coming quickly. Do you feel the current upgrade procedure using docker compose down, docker compose pull, and docker compose up addresses most of those concerns, or are there specific areas where this approach falls short for you?

Your suggestion of developing APK or RPM packages is interesting, and it sounds like you see potential benefits, especially in terms of performance and updates. I’m curious—what specific advantages do you see in moving away from Docker images? Since CoPilot relies on several other technologies like MySQL (backend database), Nginx (proxy), and Minio (file store—coming soon), we’ve found Docker helps simplify the setup, sparing users from configuring these services themselves. But I’d love to hear your thoughts on how APK or RPM packages might streamline this further. What do you think would be the biggest improvement with this shift?

You mentioned, "if you can even get CoPilot working correctly"—that caught my attention. It sounds like you’re running into some challenges. I’m curious, what specific issues have you encountered? Are there particular areas where you’re finding it hard to get things up and running?

Looking forward to hearing more about your thoughts and how we can work together to improve this!

**Comment by SecurityArsenal** [comment]
send a DM in Discord.

**Comment by taylorwalton** [comment]
@SecurityArsenal - better if you email me at `taylor.walton@socfortress.co` - I dont do a good job keeping up with discord DMs due to the number of messages I get
