### ISSUE TITLE
Rule Exclusion generator is not outputting parsable rules.

### ISSUE THREAD

**Issue by IAmRemiOS** [socfortress/CoPilot#305]
**Describe the bug**
Rule Exclusion feature is not outputting the rules with correct formatting: ex:

"<rule id=\"92156\" level=\"1\">\n  <if_sid>92156</if_sid>\n  <field name=\"win.eventdata.user\">(?i)^LAPTOP-NV34PK9O\\\\\\\\rdick$</field>\n  <field name=\"win.eventdata.originalFileName\">(?i)^VBEUI\\.DLL$</field>\n  <field name=\"win.eventdata.image\">(?i)^C:\\\\\\\\Program Files\\\\\\\\Microsoft Office\\\\\\\\root\\\\\\\\Office16\\\\\\\\EXCEL\\.EXE$</field>\n  <description>Rule to detect specific events related to EXCEL.exe loading VBEUI.DLL and executed by LAPTOP-NV34PK9O\\rdick user</description>\n  <group>sysmon, sysmon_eid7_detections, windows</group>\n</rule>"

**To Reproduce**
Set up copilot with alert exclusions as described in guides.
Select exclude rule.

**Expected behavior**
In the video this is formatted properly so you can copy paste it into wazuh, that's not the case here anymore.
**Screenshots**
![image](https://github.com/user-attachments/assets/f614c4ae-7c6b-4f67-a3ca-33a4c566708c)
![image](https://github.com/user-attachments/assets/3e389e13-5c22-45a2-8c40-d087ff5f6e23)

**Comment by taylorwalton** [comment]
Hey there! It sounds like you're seeing some inconsistencies with the rule exclusion formatting, which I can imagine is quite frustrating when you need precise output for Wazuh. Just to clarify, does this formatting issue happen consistently with the same rule, or does it vary with each analysis?

We’re relying on OpenAI for this integration, which sometimes leads to unpredictable outputs. While we can tweak the prompts, it’s tough to control the exact result every time. I’d love to hear your thoughts on how we might refine this process or if you’ve noticed any specific patterns that could help us improve the consistency.

**Comment by RemiOS0456** [comment]
While the output can vary with each analysis, I have yet to see a syntactically correct rule for Wazuh generated. Ultimately, I don't believe OpenAI alone can achieve this with 100% efficacy.

The data is already within the alert when you click 'Add Wazuh Exclusion'. For a quick and easy fix that addresses 99% of your use cases, you could pass the alert data to Wazuh, based on selectable fields. Let me give an example:

```
{
    "process_id": "25292",
    "process_name": [
        "C:\\\\Windows\\\\System32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe"
    ],
    "rule_mitre_id": "T1105",
    "rule_mitre_tactic": "Command and Control",
    "rule_mitre_technique": "Ingress Tool Transfer",
    "data_win_eventdata_user": "NT AUTHORITY\\\\SYSTEM",
    "data_win_eventdata_image": "C:\\\\Windows\\\\System32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe"
}
```

Just give me a checkbox for the fields process_name and  data_win_eventdata_image as exclusion criteria, then pass that exclusion criteria straight to GPT.

**Comment by SecurityArsenal** [comment]
There are some errors in the AI docker module.  I have them in #312 This issue can be resolved by ensuring AI knows what format to output and that it shouldn't output in a single line and not use /n.  You can also tell it not to modify the paths.  If you define what you want and the response you expect it will help.  Then a small function to clean up any errors it makes and reformat just incase it doesn't listen.

I have noticed different times of the day ChatGPT just can't follow directions my guess is load, their backups, AI is on strike!  But there are times the response is so bad the output you get is just not usable.  I have had issues with this in other projects.  I am playing with Llama 3.2 to do these tasks as it can be done all local, but does require 3TB of storage for the model.  But could allow for more automation and active response to alerts that are more consistent.

I am going to try to dig into the AI module code and see if we can improve ChatGPT by improving the prompt, but it will come at a ChatGPT API cost, but would be worth it, until o1 is released.   If you just cut the wazuh raw alert and past into GPT and give it a good prompt it will provide a good pasteable format.  The new ChatGPT-o1 is way better at this

**Comment by SecurityArsenal** [comment]
Sure, create an issue and I will start going thru the code and see if we can clean up the prompt to improve the output for now.  Then I will work on using local models.  I really think if we leverage a trained local model it could allow it to act more like an automated SOC engineer.

**Comment by SecurityArsenal** [comment]
So far seems: deepseek-coder-v2:236b-instruct-q8_0 works great and only uses 250G of space.  I will test the lower models and see if I can train a smaller model to do the same task.  I want to see if the 16b that is 8.9G can be trained.  But I think the large model can be used to do more analysis of many other areas from CoPilot.

**Comment by taylorwalton** [comment]
It sounds like you’re making significant progress with the model! I can imagine that working with 233GB of RAM must present some unique challenges. It seems like you're already thinking ahead—where do you see these models running in terms of infrastructure?

When you say "works great," I’m curious—what specifically are you referring to? Are you noticing improvements in performance, accuracy, or speed? I want to make sure I understand how this model is impacting your results. Is it that using this model within [CoPilot-AI-Module](https://github.com/socfortress/CoPilot-AI-Module) is leading to the desired outcomes, or are there other areas you're exploring?

Looking forward to hearing more about your findings.

**Comment by SecurityArsenal** [comment]
I am trying to get the model down small enough that it can run on a normal system, but it will need to have a GPU that can support AI.  I was thinking this would be an optional module that will allow AI within the CoPilot system.  So it will do the research on Alerts collect the data from the Agents, grab any relevant information from the internet, write test code to confirm a vulnerability.  Try to automate as much as we can and truly alert on real issues.  We could even have it auto remediate Alerts.  Example run the code in a sandbox and take the changes the code made to clearly ensure it removes all the change the code made to a system, then audit that it doesn't come back.  As attacks get more sophisticated if one method is deleted the persistent hook will deploy a new method.  AI is changing the landscape of how fast an attack can happen, by automating the attack too.  So real-time response is becoming more required.  Because an AI attack will find new attack vectors and generate code and attack so fast a human can't keep up.

Yes, the large model had no issue generating the wazuh exclude rule.  So does 1o-preview, so when that is available it might be a good option,  4o can do it well, but does require a much more robust prompt and provide good examples with the prompt so it stays in the required response we expect.

So I am exploring expanding AI to the whole CoPilot system that will do things as fast as possible without an engineer being needed.  Then the engineer will be sent alerts and updates based on the current state of things.  Maybe an iOS android APP that the AI can talk to the engineer and get guidance on what it should do.  I have lots of ideas and still working thru design and how to tie into CoPilot.  I think you have rolled all the Alerts into the graylog_0 index.   Is that correct?  It use to show them under each index for each customer.   I think it is better to roll them together anyway, but maybe order them by risk level. This way when AI does investigate it will process the highest risk first.  For large networks have a pool of AI servers that can process many Alerts at once to speed up things.

**Comment by taylorwalton** [comment]
First, I want to sincerely apologize for missing your previous message. I’ve seen one other user mention emails being missed and it was a result of my email service quarantining the message, and I’m starting to wonder if that’s what happened with yours. Could you please confirm your email address for me so I can double-check and ensure you are added as a safe sender? I definitely don’t want this to happen again.

As for your thoughts on expanding the AI capabilities within the CoPilot system, it sounds like you're envisioning something transformative. If I understand correctly, you’re aiming to integrate AI that can handle everything from researching alerts, collecting data, testing code, automating responses, and even remediating issues in real-time. The idea of AI running code in a sandbox and ensuring complete remediation is a brilliant way to tackle increasingly sophisticated attacks. Does that accurately capture your vision?

I’m particularly intrigued by your suggestion to create a module that could plug CoPilot into hardware applicable for AI models. I wonder if we should explore the idea of building a modular AI component that can not only integrate with systems that support GPUs but also potentially expand its flexibility to run on other hardware platforms. This could open up more opportunities for broader deployment. What are your thoughts on making it more adaptable in that way?

Your insights on prioritizing alerts based on risk level and using AI to clean up and enhance the alert details make a lot of sense. Especially with AI automating these processes, it would drastically reduce the time engineers need to spend filtering through false positives and low-priority alerts. That’s key, particularly in a landscape where speed is critical to responding to attacks.

It seems like you're thinking about tying this into CoPilot across various platforms, including iOS and Android, which would be incredibly useful for engineers on the go. How do you see the engineer-AI communication working? Would the AI be making suggestions that engineers can approve, or would it be seeking real-time guidance from them?

Regarding the changes in the alert indexing, yes, we did roll all the alerts into the graylog_0 index to centralize things and simplify the process. I agree that sorting them by risk level makes a lot of sense, especially if AI is prioritizing the highest risks first.

Let’s definitely schedule a call to go over these ideas more thoroughly. I’m excited about where this can go, and I’d love to collaborate on refining the design and execution. I'm out of town next week but will be back the 14th.

Looking forward to your thoughts and our discussion.
